<?php
/**
 * VolunteerOps - Telegram Bot Integration
 * Free broadcast channel (Bot API has no send cost or volume fee, unlike
 * Viber/WhatsApp business messaging) used by mobilization.php's "Άμεση
 * Κινητοποίηση" button and by each volunteer's Telegram link on
 * notification-preferences.php.
 *
 * Linking handshake: a volunteer never types anything into VolunteerOps to
 * connect - they open https://t.me/<bot>?start=<token> (generated by
 * generateTelegramLinkToken()), Telegram sends "/start <token>" to
 * telegram-webhook.php, which resolves the token back to a user_id and
 * stores chat_id. Sending a message later only needs that stored chat_id -
 * no further Telegram-side permission step exists.
 */

if (!defined('VOLUNTEEROPS')) die('Direct access not permitted');

function isTelegramConfigured(): bool {
    return trim(getSetting('telegram_bot_token', '')) !== '' && trim(getSetting('telegram_bot_username', '')) !== '';
}

function getTelegramDeepLink(string $token): ?string {
    $username = trim(getSetting('telegram_bot_username', ''));
    if ($username === '') return null;
    return 'https://t.me/' . $username . '?start=' . $token;
}

/**
 * One pending token per user - regenerating silently drops any earlier one,
 * so an abandoned "Σύνδεση" click can never be replayed later.
 */
function generateTelegramLinkToken(int $userId): string {
    $token = bin2hex(random_bytes(24));
    dbExecute("DELETE FROM telegram_link_tokens WHERE user_id = ?", [$userId]);
    dbExecute("INSERT INTO telegram_link_tokens (token, user_id, created_at) VALUES (?, ?, NOW())", [$token, $userId]);
    return $token;
}

/**
 * Tokens are single-use and only meant to survive the few seconds it takes
 * Telegram to open - 15 minutes covers a slow app-switch without leaving a
 * long-lived credential lying around.
 */
function consumeTelegramLinkToken(string $token): ?int {
    $row = dbFetchOne(
        "SELECT user_id FROM telegram_link_tokens WHERE token = ? AND created_at >= DATE_SUB(NOW(), INTERVAL 15 MINUTE)",
        [$token]
    );
    dbExecute("DELETE FROM telegram_link_tokens WHERE token = ?", [$token]);
    return $row ? (int) $row['user_id'] : null;
}

/**
 * Raw Bot API call. Returns the decoded response body even on a Telegram-side
 * error (e.g. ok:false, error_code:403) so callers can branch on it - only
 * returns null when the request itself couldn't be made (no token, no cURL,
 * network failure).
 */
function tgApiCall(string $method, array $params = [], ?string $tokenOverride = null): ?array {
    $token = $tokenOverride ?? trim(getSetting('telegram_bot_token', ''));
    if ($token === '' || !function_exists('curl_init')) return null;

    $ch = curl_init("https://api.telegram.org/bot{$token}/{$method}");
    curl_setopt_array($ch, [
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => json_encode($params),
        CURLOPT_HTTPHEADER     => ['Content-Type: application/json'],
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 15,
        CURLOPT_SSL_VERIFYPEER => true,
    ]);
    $response = curl_exec($ch);
    $curlErr  = curl_error($ch);
    curl_close($ch);

    if ($response === false) {
        error_log("Telegram API transport error ({$method}): {$curlErr}");
        return null;
    }
    $decoded = json_decode($response, true);
    return is_array($decoded) ? $decoded : null;
}

/**
 * Plain text only (no parse_mode) - an admin-typed broadcast can contain
 * underscores/asterisks/angle brackets that would otherwise be parsed as
 * Markdown/HTML and silently mangle the message or make sendMessage 400.
 */
function sendTelegramMessage($chatId, string $text): bool {
    $result = tgApiCall('sendMessage', ['chat_id' => $chatId, 'text' => $text]);
    return $result !== null && !empty($result['ok']);
}

/**
 * Sends to every user with a linked chat_id. A 403 (Forbidden: bot was
 * blocked by the user) or the chat no longer existing means that link is
 * dead, so it's cleared here the same way push_subscriptions rows get
 * cleaned up on an expired endpoint - otherwise every future broadcast keeps
 * re-failing against the same stale chat_id forever.
 */
function sendTelegramBroadcast(string $text): array {
    $recipients = dbFetchAll(
        "SELECT id, telegram_chat_id FROM users
          WHERE telegram_chat_id IS NOT NULL AND is_active = 1 AND deleted_at IS NULL"
    );

    $delivered = 0;
    $failed = 0;
    foreach ($recipients as $recipient) {
        $result = tgApiCall('sendMessage', ['chat_id' => $recipient['telegram_chat_id'], 'text' => $text]);

        if ($result !== null && !empty($result['ok'])) {
            $delivered++;
        } else {
            $failed++;
            $errorCode = $result['error_code'] ?? null;
            if ($errorCode === 403 || $errorCode === 400) {
                dbExecute(
                    "UPDATE users SET telegram_chat_id = NULL, telegram_username = NULL, telegram_linked_at = NULL WHERE id = ?",
                    [$recipient['id']]
                );
            }
        }

        // Telegram allows ~30 messages/second across different chats - this
        // keeps a large volunteer list well under that without needing a
        // queue/cron for what is, in practice, at most a few hundred sends.
        usleep(40000);
    }

    return [
        'recipients' => count($recipients),
        'delivered'  => $delivered,
        'failed'     => $failed,
    ];
}

/**
 * (Re-)registers telegram-webhook.php with Telegram so /start messages start
 * arriving. Called right after a valid bot token is saved in settings.php -
 * pass that token explicitly as $tokenOverride rather than letting tgApiCall()
 * fall back to getSetting('telegram_bot_token'): getSetting()'s cache is
 * static-per-request and bootstrap.php's maintenance-mode check already
 * primes it (with the OLD, pre-save value) before settings.php's own code
 * ever runs, so on the very first save the fallback would silently read
 * empty and this call would fail even though the token was just persisted.
 * The secret_token round-trips back on every webhook POST as the
 * X-Telegram-Bot-Api-Secret-Token header - that's the only auth the webhook
 * has, since it's a public endpoint Telegram's servers call directly.
 */
function registerTelegramWebhook(?string $tokenOverride = null): bool {
    $secret = trim(getSetting('telegram_webhook_secret', ''));
    if ($secret === '') {
        $secret = bin2hex(random_bytes(32));
        dbExecute(
            "INSERT INTO settings (setting_key, setting_value, created_at, updated_at) VALUES ('telegram_webhook_secret', ?, NOW(), NOW())
             ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)",
            [$secret]
        );
    }

    $url = rtrim(BASE_URL, '/') . '/telegram-webhook.php';
    $result = tgApiCall('setWebhook', [
        'url' => $url,
        'secret_token' => $secret,
        'allowed_updates' => ['message'],
    ], $tokenOverride);

    return $result !== null && !empty($result['ok']);
}
